title: "Alireza Irandoost"
<<<<<<< HEAD
email: "your.email@example.com"
description: "Electronic Engineer – Optoelectronics & Biophotonics"
baseurl: ""
url: "https://alireza-irandoost.github.io"
theme: minimal-mistakes-jekyll

author:
  name: "Alireza Irandoost"
  email: "your.email@example.com"
=======
email: "you@example.com"  # ← replace with your real email
description: >- 
  I’m an Electronic Engineer with a passion for optoelectronics and biophotonics. 
  I completed my master’s in Micro and Nanoelectronic Devices at Sharif University of Technology.
url: "https://yourusername.github.io"  # ← replace with your GitHub username
baseurl: "" 

author:
  name: "Alireza Irandoost"
  email: "you@example.com"

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "default"
>>>>>>> fce142cef331cd94f233f00e8dcb528677f9ab85

plugins:
  - jekyll-feed
  - jekyll-seo-tag

<<<<<<< HEAD
minimal_mistakes_skin: "default"

header_pages:
  - _pages/about.md
  - _pages/cv.md
  - _pages/projects.md
=======
# Navigation bar links
header_pages:
  - _pages/about.md
  - _pages/cv.md
  - _pages/projects.md

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"  # ← replace
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"  # ← replace
>>>>>>> fce142cef331cd94f233f00e8dcb528677f9ab85
